### PR TITLE
New tests

### PR DESCRIPTION
**Pull request by Zyqsempai**

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@MrHash I think that we can merge this into develop, here is only new tests for Query.php file, in next step i will fix Elastica dependencies in this file, in our "uow" branch.

**Comment by MrHash** [comment]
OK but failing tests. Also how come there are repeating commits in the pull request?

**Comment by Zyqsempai** [comment]
@MrHash I will fix tests in few minutes, about repeating commits, it's strange i just made rebase on develop branch.

**Comment by MrHash** [comment]
When moving ahead with a refactoring of the UoW please discuss your approach in the issue so we can agree on the solution. thanks

**Comment by Zyqsempai** [comment]
@MrHash No problem, thanks.

**Pull request merged**
