### PR TITLE
New test for UnitOfWork

### PR DESCRIPTION
**Pull request by Zyqsempai**
First step to make UnitOfWork independent from Elastica

### CODE REVIEW

**Comment by Zyqsempai** [comment]
@MrHash, can you merge this one?Or some one?

**Comment by MrHash** [comment]
Hey i'm reorganising things a little. The previous master head is now 0.1, and the develop branch is now 0.2. So master and develop is at 0.2. If you are ok with the new 0.2 updates we can pull this into the develop branch

**Comment by MrHash** [comment]
I can also create a feature branch for decoupling the UoW if you like

**Comment by Zyqsempai** [comment]
@MrHash, Hi, glad you are here. I think you are right and we can merge tests into develop, and it will be nice to have branch for feature refactoring! Thank you, i will prepare next part of tests.

**Comment by MrHash** [comment]
Ok you have to close this pull request and create a new one into develop please. then lets create issues for each feature and organise the development. i guess the first is #85 ?

**Comment by Zyqsempai** [comment]
Done, yep, i think this is quiet enough for first issue, the second one can be same issue but for Query class, same abstraction problem, and the third can be some kind of abstraction for Document. The main problem we have on this moment is dependence from Elastica. That what i noticed first of all.

**Pull request closed without merging**
